set_property IOSTANDARD LVCMOS33 [get_ports *]
set_property PACKAGE_PIN P17 [get_ports {clk}]

set_property PACKAGE_PIN F5 [get_ports {red[0]}]
set_property PACKAGE_PIN C6 [get_ports {red[1]}]
set_property PACKAGE_PIN C5 [get_ports {red[2]}]
set_property PACKAGE_PIN B7 [get_ports {red[3]}]

set_property PACKAGE_PIN B6 [get_ports {green[0]}]
set_property PACKAGE_PIN A6 [get_ports {green[1]}]
set_property PACKAGE_PIN A5 [get_ports {green[2]}]
set_property PACKAGE_PIN D8 [get_ports {green[3]}]

set_property PACKAGE_PIN C7 [get_ports {blue[0]}]
set_property PACKAGE_PIN E6 [get_ports {blue[1]}]
set_property PACKAGE_PIN E5 [get_ports {blue[2]}]
set_property PACKAGE_PIN E7 [get_ports {blue[3]}]

set_property PACKAGE_PIN D7 [get_ports {hsync}]
set_property PACKAGE_PIN C4 [get_ports {vsync}]

set_property PACKAGE_PIN U4 [get_ports {reset}]
set_property PACKAGE_PIN R17 [get_ports {btn_jmp}]
set_property PACKAGE_PIN G4 [get_ports {led_pause}]
set_property PACKAGE_PIN G3 [get_ports {led_failed}]
set_property PACKAGE_PIN K2 [get_ports {led_jmp}]
set_property PACKAGE_PIN J4 [get_ports {led_score}]


set_property PACKAGE_PIN K1 [get_ports {led_level[0]}]
set_property PACKAGE_PIN H6 [get_ports {led_level[1]}]
set_property PACKAGE_PIN H5 [get_ports {led_level[2]}]
set_property PACKAGE_PIN J5 [get_ports {led_level[3]}]
set_property PACKAGE_PIN K6 [get_ports {led_level[4]}]
set_property PACKAGE_PIN L1 [get_ports {led_level[5]}]
set_property PACKAGE_PIN M1 [get_ports {led_level[6]}]
set_property PACKAGE_PIN K3 [get_ports {led_level[7]}]

set_property PACKAGE_PIN V1 [get_ports {btn_l_level}]
set_property PACKAGE_PIN R11 [get_ports {btn_h_level}]


set_property PACKAGE_PIN D4 [get_ports {led_dest_1[7]}]
set_property PACKAGE_PIN E3 [get_ports {led_dest_1[6]}]
set_property PACKAGE_PIN D3 [get_ports {led_dest_1[5]}]
set_property PACKAGE_PIN F4 [get_ports {led_dest_1[4]}]
set_property PACKAGE_PIN F3 [get_ports {led_dest_1[3]}]
set_property PACKAGE_PIN E2 [get_ports {led_dest_1[2]}]
set_property PACKAGE_PIN D2 [get_ports {led_dest_1[1]}]
set_property PACKAGE_PIN H2 [get_ports {led_dest_1[0]}]


set_property PACKAGE_PIN B4 [get_ports {led_dest_2[7]}]
set_property PACKAGE_PIN A4 [get_ports {led_dest_2[6]}]
set_property PACKAGE_PIN A3 [get_ports {led_dest_2[5]}]
set_property PACKAGE_PIN B1 [get_ports {led_dest_2[4]}]
set_property PACKAGE_PIN A1 [get_ports {led_dest_2[3]}]
set_property PACKAGE_PIN B3 [get_ports {led_dest_2[2]}]
set_property PACKAGE_PIN B2 [get_ports {led_dest_2[1]}]
set_property PACKAGE_PIN D5 [get_ports {led_dest_2[0]}]


set_property PACKAGE_PIN G2 [get_ports {led_en[7]}]
set_property PACKAGE_PIN C2 [get_ports {led_en[6]}]
set_property PACKAGE_PIN C1 [get_ports {led_en[5]}]
set_property PACKAGE_PIN H1 [get_ports {led_en[4]}]
set_property PACKAGE_PIN G1 [get_ports {led_en[3]}]
set_property PACKAGE_PIN F1 [get_ports {led_en[2]}]
set_property PACKAGE_PIN E1 [get_ports {led_en[1]}]
set_property PACKAGE_PIN G6 [get_ports {led_en[0]}]

#Allowing Randomizer to be successfully generated
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets randomizer/*]
#set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets randomizer/p_101_in]
#set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets randomizer/p_105_in]
#set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets randomizer/p_109_in]
#set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets randomizer/p_113_in]
#set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets randomizer/p_117_in]
#set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets randomizer/p_121_in]
#set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets randomizer/p_124_in]
#set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets randomizer/p_134_in]
#set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets randomizer/p_13_in]
#set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets randomizer/p_17_in]
#set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets randomizer/p_21_in]
#set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets randomizer/p_25_in]
#set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets randomizer/p_29_in]
#set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets randomizer/p_33_in]
#set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets randomizer/p_37_in]
#set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets randomizer/p_41_in]
#set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets randomizer/p_45_in]
#set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets randomizer/p_49_in]
#set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets randomizer/p_53_in]
#set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets randomizer/p_57_in]
#set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets randomizer/p_5_in]
#set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets randomizer/p_61_in]
#set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets randomizer/p_65_in]
#set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets randomizer/p_69_in]
#set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets randomizer/p_73_in]
#set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets randomizer/p_77_in]
#set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets randomizer/p_81_in]
#set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets randomizer/p_85_in]
#set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets randomizer/p_89_in]
#set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets randomizer/p_93_in]
#set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets randomizer/p_97_in]
#set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets randomizer/p_9_in]
#set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets randomizer/slg_31]